// data/days_1_50.js
// Bible-in-a-Year, Days 1-50

export const days = [
  { day: 1, oldTestament: "Genesis 1-3", newTestament: "Matthew 1", reflection: "God creates the heavens and the earth, establishing order and life.", prompt: "What aspect of creation speaks to you today?" },
  { day: 2, oldTestament: "Genesis 4-6", newTestament: "Matthew 2", reflection: "Humanity struggles and choices have consequences, yet God’s plan continues.", prompt: "How do you see God’s patience and mercy reflected today?" },
  { day: 3, oldTestament: "Genesis 7-9", newTestament: "Matthew 3", reflection: "The flood shows God’s justice and His covenant of hope.", prompt: "Reflect on a time you experienced both judgment and grace." },
  { day: 4, oldTestament: "Genesis 10-12", newTestament: "Matthew 4", reflection: "God calls Abraham, inviting faith and obedience.", prompt: "How can you respond to God’s call in your life today?" },
  { day: 5, oldTestament: "Genesis 13-15", newTestament: "Matthew 5", reflection: "Faith and trust in God are foundational.", prompt: "What step of faith can you take today?" },
  { day: 6, oldTestament: "Genesis 16-18", newTestament: "Matthew 6", reflection: "God’s promises and guidance challenge us to live rightly.", prompt: "How can you practice integrity and obedience today?" },
  { day: 7, oldTestament: "Genesis 19-21", newTestament: "Matthew 7", reflection: "Lessons of faith and divine provision are evident.", prompt: "Where do you see God’s provision in your life?" },
  { day: 8, oldTestament: "Genesis 22-24", newTestament: "Matthew 8", reflection: "Abraham’s faith is tested, reminding us to trust fully.", prompt: "In what area do you need to trust God completely?" },
  { day: 9, oldTestament: "Genesis 25-27", newTestament: "Matthew 9", reflection: "God continues His plan through the next generation.", prompt: "How can you be faithful in your responsibilities today?" },
  { day: 10, oldTestament: "Genesis 28-30", newTestament: "Matthew 10", reflection: "Jacob’s journey teaches perseverance and divine protection.", prompt: "How do you trust God when life feels uncertain?" },
  { day: 11, oldTestament: "Genesis 31-33", newTestament: "Matthew 11", reflection: "God guides Jacob and shows reconciliation.", prompt: "Where do you need reconciliation in your life?" },
  { day: 12, oldTestament: "Genesis 34-36", newTestament: "Matthew 12", reflection: "Life’s challenges test our faith, yet God provides guidance.", prompt: "How do you seek God’s wisdom in difficult situations?" },
  { day: 13, oldTestament: "Genesis 37-39", newTestament: "Matthew 13", reflection: "Joseph’s story shows God’s providence through trials.", prompt: "Reflect on a time when a challenge later brought good." },
  { day: 14, oldTestament: "Genesis 40-42", newTestament: "Matthew 14", reflection: "Trusting God in prison or hardship leads to eventual blessing.", prompt: "How can you remain faithful in waiting periods?" },
  { day: 15, oldTestament: "Genesis 43-45", newTestament: "Matthew 15", reflection: "Forgiveness and providence restore relationships.", prompt: "Who do you need to forgive today?" },
  { day: 16, oldTestament: "Genesis 46-48", newTestament: "Matthew 16", reflection: "God’s promises extend through generations.", prompt: "How can you live faithfully for future generations?" },
  { day: 17, oldTestament: "Genesis 49-50", newTestament: "Matthew 17", reflection: "God’s plan works even in endings and farewells.", prompt: "What endings in your life can you trust God with?" },
  { day: 18, oldTestament: "Exodus 1-3", newTestament: "Matthew 18", reflection: "God calls leaders to deliver His people.", prompt: "How can you respond to God’s calling in your life?" },
  { day: 19, oldTestament: "Exodus 4-6", newTestament: "Matthew 19", reflection: "God equips those He calls for His purposes.", prompt: "What resources or gifts has God given you to serve Him?" },
  { day: 20, oldTestament: "Exodus 7-9", newTestament: "Matthew 20", reflection: "God’s power brings liberation and demonstrates His justice.", prompt: "Where do you need God’s power to intervene?" },
  { day: 21, oldTestament: "Exodus 10-12", newTestament: "Matthew 21", reflection: "God’s protection and faithfulness are clear through obedience.", prompt: "How can you practice obedience today?" },
  { day: 22, oldTestament: "Exodus 13-15", newTestament: "Matthew 22", reflection: "God leads His people through challenges with faithfulness.", prompt: "What steps of faith are you taking today?" },
  { day: 23, oldTestament: "Exodus 16-18", newTestament: "Matthew 23", reflection: "God provides daily for His people.", prompt: "Where do you see God’s provision in your own life?" },
  { day: 24, oldTestament: "Exodus 19-21", newTestament: "Matthew 24", reflection: "God’s law guides us to live rightly and justly.", prompt: "How can you align your life more with God’s will?" },
  { day: 25, oldTestament: "Exodus 22-24", newTestament: "Matthew 25", reflection: "God’s covenant calls for obedience and faithfulness.", prompt: "What promises of God encourage you today?" },
  { day: 26, oldTestament: "Exodus 25-27", newTestament: "Matthew 26", reflection: "God provides ways to approach Him in holiness.", prompt: "How can you honor God in your daily routines?" },
  { day: 27, oldTestament: "Exodus 28-30", newTestament: "Matthew 27", reflection: "God’s presence and guidance are central to His people.", prompt: "Where do you seek God’s presence most?" },
  { day: 28, oldTestament: "Exodus 31-33", newTestament: "Matthew 28", reflection: "God continues to lead and renew His covenant.", prompt: "How do you trust God to guide your next steps?" },
  { day: 29, oldTestament: "Exodus 34-36", newTestament: "Mark 1", reflection: "God’s glory is revealed and His instructions matter.", prompt: "Where can you reflect God’s glory today?" },
  { day: 30, oldTestament: "Exodus 37-40", newTestament: "Mark 2", reflection: "God provides detailed guidance for worship and holiness.", prompt: "How can you worship God fully in your day?" },
  { day: 31, oldTestament: "Leviticus 1-4", newTestament: "Mark 3", reflection: "God calls His people to purity and reverence.", prompt: "What area of your life needs purification today?" },
  { day: 32, oldTestament: "Leviticus 5-7", newTestament: "Mark 4", reflection: "God provides ways to atone and reconcile.", prompt: "Where do you need reconciliation with God or others?" },
  { day: 33, oldTestament: "Leviticus 8-10", newTestament: "Mark 5", reflection: "God sets apart His people for holy purposes.", prompt: "How can you live a holy life today?" },
  { day: 34, oldTestament: "Leviticus 11-13", newTestament: "Mark 6", reflection: "God teaches care and discernment.", prompt: "What discernment do you need in your decisions today?" },
  { day: 35, oldTestament: "Leviticus 14-15", newTestament: "Mark 7", reflection: "God’s laws show His concern for health and purity.", prompt: "Where can you practice spiritual or personal hygiene in life?" },
  { day: 36, oldTestament: "Leviticus 16-18", newTestament: "Mark 8", reflection: "God’s instructions show mercy and justice.", prompt: "How can you show mercy to others today?" },
  { day: 37, oldTestament: "Leviticus 19-21", newTestament: "Mark 9", reflection: "God calls His people to live justly and love others.", prompt: "Who can you serve or show justice to today?" },
  { day: 38, oldTestament: "Leviticus 22-23", newTestament: "Mark 10", reflection: "God’s holy days remind us to rest and worship.", prompt: "How will you honor God with your time today?" },
  { day: 39, oldTestament: "Leviticus 24-25", newTestament: "Mark 11", reflection: "God teaches fairness, justice, and care for the poor.", prompt: "Who can you support or help in need today?" },
  { day: 40, oldTestament: "Leviticus 26-27", newTestament: "Mark 12", reflection: "Obedience brings blessing, rebellion brings consequences.", prompt: "Where do you need to obey God more fully?" },
  { day: 41, oldTestament: "Numbers 1-2", newTestament: "Mark 13", reflection: "God organizes and equips His people for purpose.", prompt: "How can you be better organized in following God’s plan?" },
  { day: 42, oldTestament: "Numbers 3-4", newTestament: "Mark 14", reflection: "God sets roles and responsibilities for His work.", prompt: "What role has God called you to serve?" },
  { day: 43, oldTestament: "Numbers 5-6", newTestament: "Mark 15", reflection: "God teaches accountability and vows.", prompt: "Are there promises you need to keep faithfully today?" },
  { day: 44, oldTestament: "Numbers 7-8", newTestament: "Mark 16", reflection: "God provides ways to worship and give offerings.", prompt: "How can you give back to God today?" },
  { day: 45, oldTestament: "Numbers 9-10", newTestament: "Luke 1", reflection: "God leads His people with guidance and signs.", prompt: "Where do you need God’s guidance today?" },
  { day: 46, oldTestament: "Numbers 11-12", newTestament: "Luke 2", reflection: "God shows patience even when people complain.", prompt: "How can you practice patience today?" },
  { day: 47, oldTestament: "Numbers 13-14", newTestament: "Luke 3", reflection: "Faith and courage are required to follow God’s path.", prompt: "What step of faith can you take today?" },
  { day: 48, oldTestament: "Numbers 15-16", newTestament: "Luke 4", reflection: "God demonstrates justice and mercy.", prompt: "Where can you show mercy while standing for truth?" },
  { day: 49, oldTestament: "Numbers 17-18", newTestament: "Luke 5", reflection: "God appoints leaders for His purpose.", prompt: "How can you support God’s leaders today?" },
  { day: 50, oldTestament: "Numbers 19-20", newTestament: "Luke 6", reflection: "God’s instructions sustain life and faith.", prompt: "How can you trust God’s instructions today?" },
  { day: 51, oldTestament: "Numbers 21-22", newTestament: "Luke 7", reflection: "God protects and delivers His people through challenges.", prompt: "Where do you need God’s protection today?" },
{ day: 52, oldTestament: "Numbers 23-25", newTestament: "Luke 8", reflection: "God’s blessings come to those who follow His ways.", prompt: "How can you follow God’s ways more fully?" },
{ day: 53, oldTestament: "Numbers 26-27", newTestament: "Luke 9", reflection: "God establishes leadership and succession for His purposes.", prompt: "Who can you mentor or support in faith today?" },
{ day: 54, oldTestament: "Numbers 28-30", newTestament: "Luke 10", reflection: "God values worship, vows, and commitment.", prompt: "What commitment can you renew to God today?" },
{ day: 55, oldTestament: "Numbers 31-32", newTestament: "Luke 11", reflection: "God guides victory and fair judgment.", prompt: "How do you seek God’s guidance in decisions?" },
{ day: 56, oldTestament: "Numbers 33-34", newTestament: "Luke 12", reflection: "God leads His people step by step.", prompt: "How do you trust God’s timing in your life?" },
{ day: 57, oldTestament: "Numbers 35-36", newTestament: "Luke 13", reflection: "God provides refuge and justice.", prompt: "Where do you need God’s justice today?" },
{ day: 58, oldTestament: "Deuteronomy 1-2", newTestament: "Luke 14", reflection: "God’s faithfulness leads His people through challenges.", prompt: "How can you remain faithful during trials?" },
{ day: 59, oldTestament: "Deuteronomy 3-4", newTestament: "Luke 15", reflection: "God’s laws guide His people in righteousness.", prompt: "Which of God’s commands can guide you today?" },
{ day: 60, oldTestament: "Deuteronomy 5-6", newTestament: "Luke 16", reflection: "God calls for wholehearted love and devotion.", prompt: "How can you love God more fully today?" },
{ day: 61, oldTestament: "Deuteronomy 7-8", newTestament: "Luke 17", reflection: "God reminds us to rely on Him and not our own strength.", prompt: "Where do you need to depend on God today?" },
{ day: 62, oldTestament: "Deuteronomy 9-10", newTestament: "Luke 18", reflection: "God’s mercy is greater than our shortcomings.", prompt: "How have you experienced God’s mercy recently?" },
{ day: 63, oldTestament: "Deuteronomy 11-12", newTestament: "Luke 19", reflection: "Obedience leads to blessing and life.", prompt: "What step of obedience can you take today?" },
{ day: 64, oldTestament: "Deuteronomy 13-14", newTestament: "Luke 20", reflection: "God warns against false worship.", prompt: "Where might you need to refocus your heart on God?" },
{ day: 65, oldTestament: "Deuteronomy 15-16", newTestament: "Luke 21", reflection: "God calls for generosity and justice.", prompt: "Who can you bless today through generosity?" },
{ day: 66, oldTestament: "Deuteronomy 17-18", newTestament: "Luke 22", reflection: "God provides guidance and leaders to serve His people.", prompt: "How do you seek God’s guidance in leadership?" },
{ day: 67, oldTestament: "Deuteronomy 19-20", newTestament: "Luke 23", reflection: "God upholds justice and fairness.", prompt: "Where can you practice fairness in your life?" },
{ day: 68, oldTestament: "Deuteronomy 21-22", newTestament: "Luke 24", reflection: "God’s instructions protect and preserve life.", prompt: "What area of your life requires protection through God’s guidance?" },
{ day: 69, oldTestament: "Deuteronomy 23-24", newTestament: "John 1", reflection: "God cares about holiness and community.", prompt: "How can you foster holiness and unity today?" },
{ day: 70, oldTestament: "Deuteronomy 25-26", newTestament: "John 2", reflection: "God calls us to honest and faithful living.", prompt: "Where can you practice faithfulness today?" },
{ day: 71, oldTestament: "Deuteronomy 27-28", newTestament: "John 3", reflection: "Blessings and consequences follow obedience and disobedience.", prompt: "How can you align your choices with God’s will?" },
{ day: 72, oldTestament: "Deuteronomy 29-30", newTestament: "John 4", reflection: "God gives us freedom to choose life and blessing.", prompt: "What choice of life will you make today?" },
{ day: 73, oldTestament: "Deuteronomy 31-32", newTestament: "John 5", reflection: "God’s words endure as guidance for generations.", prompt: "Which scripture can guide you today?" },
{ day: 74, oldTestament: "Deuteronomy 33-34", newTestament: "John 6", reflection: "God blesses His people and calls them to faithfulness.", prompt: "Where do you see God’s blessing in your life?" },
{ day: 75, oldTestament: "Joshua 1-3", newTestament: "John 7", reflection: "God leads courageously into new territories.", prompt: "What new step can you take in faith?" },
{ day: 76, oldTestament: "Joshua 4-6", newTestament: "John 8", reflection: "God’s power delivers and gives victory.", prompt: "Where do you need God’s deliverance today?" },
{ day: 77, oldTestament: "Joshua 7-9", newTestament: "John 9", reflection: "God’s justice requires integrity.", prompt: "How can you practice integrity today?" },
{ day: 78, oldTestament: "Joshua 10-12", newTestament: "John 10", reflection: "God fights for His people and fulfills His promises.", prompt: "What promise of God do you trust today?" },
{ day: 79, oldTestament: "Joshua 13-15", newTestament: "John 11", reflection: "God’s inheritance is given to His faithful.", prompt: "What area of your life is God calling you to steward faithfully?" },
{ day: 80, oldTestament: "Joshua 16-18", newTestament: "John 12", reflection: "God divides the land according to His plan.", prompt: "How can you follow God’s plan in your decisions?" },
{ day: 81, oldTestament: "Joshua 19-21", newTestament: "John 13", reflection: "God’s instructions provide order and blessing.", prompt: "Where can you apply God’s order in your life?" },
{ day: 82, oldTestament: "Joshua 22-24", newTestament: "John 14", reflection: "God calls His people to faithfulness and covenant.", prompt: "How can you renew your covenant with God?" },
{ day: 83, oldTestament: "Judges 1-3", newTestament: "John 15", reflection: "God raises leaders to deliver His people.", prompt: "Where do you need God’s leadership today?" },
{ day: 84, oldTestament: "Judges 4-6", newTestament: "John 16", reflection: "God empowers those who trust Him.", prompt: "How can you rely on God’s strength today?" },
{ day: 85, oldTestament: "Judges 7-9", newTestament: "John 17", reflection: "God’s guidance leads to victory.", prompt: "Where can you seek God’s guidance today?" },
{ day: 86, oldTestament: "Judges 10-12", newTestament: "John 18", reflection: "God delivers His people through faithfulness.", prompt: "How can you remain faithful under pressure?" },
{ day: 87, oldTestament: "Judges 13-15", newTestament: "John 19", reflection: "God’s plan works through imperfect people.", prompt: "Where can you trust God despite your weakness?" },
{ day: 88, oldTestament: "Judges 16-18", newTestament: "John 20", reflection: "God’s power is greater than human strength.", prompt: "What challenge requires God’s strength in your life?" },
{ day: 89, oldTestament: "Judges 19-21", newTestament: "John 21", reflection: "God provides justice and restoration.", prompt: "Where do you seek God’s restoration today?" },
{ day: 90, oldTestament: "Ruth 1-4", newTestament: "Acts 1", reflection: "God’s faithfulness rewards loyalty and love.", prompt: "Who can you show faithfulness or kindness to today?" },
{ day: 91, oldTestament: "1 Samuel 1-3", newTestament: "Acts 2", reflection: "God hears prayers and calls His people.", prompt: "What prayer do you need to lift to God today?" },
{ day: 92, oldTestament: "1 Samuel 4-6", newTestament: "Acts 3", reflection: "God demonstrates power and presence.", prompt: "Where do you need God’s presence in your life?" },
{ day: 93, oldTestament: "1 Samuel 7-9", newTestament: "Acts 4", reflection: "God raises leaders and prepares His people.", prompt: "How can you support God’s chosen leaders?" },
{ day: 94, oldTestament: "1 Samuel 10-12", newTestament: "Acts 5", reflection: "God calls for obedience and faith.", prompt: "Where can you practice obedience today?" },
{ day: 95, oldTestament: "1 Samuel 13-15", newTestament: "Acts 6", reflection: "God judges disobedience and rewards faithfulness.", prompt: "How can you remain faithful in your duties?" },
{ day: 96, oldTestament: "1 Samuel 16-17", newTestament: "Acts 7", reflection: "God empowers the weak to accomplish great things.", prompt: "What weakness can you surrender to God today?" },
{ day: 97, oldTestament: "1 Samuel 18-20", newTestament: "Acts 8", reflection: "God guides friendship, loyalty, and leadership.", prompt: "How can you practice loyalty and faithfulness today?" },
{ day: 98, oldTestament: "1 Samuel 21-24", newTestament: "Acts 9", reflection: "God protects and directs His people in challenging times.", prompt: "Where do you need God’s direction or protection?" },
{ day: 99, oldTestament: "1 Samuel 25-27", newTestament: "Acts 10", reflection: "God’s wisdom prevents unnecessary conflict.", prompt: "How can you seek God’s wisdom in relationships today?" },
{ day: 100, oldTestament: "1 Samuel 28-31", newTestament: "Acts 11", reflection: "God’s plan continues even through difficult endings.", prompt: "What ending can you trust God with today?" }, 
  { day: 101, oldTestament: "2 Samuel 1-3", newTestament: "Acts 12", reflection: "God preserves His plans even through leadership transitions.", prompt: "How can you trust God during times of change?" },
{ day: 102, oldTestament: "2 Samuel 4-6", newTestament: "Acts 13", reflection: "God brings His presence among His people.", prompt: "Where do you need God’s presence today?" },
{ day: 103, oldTestament: "2 Samuel 7-9", newTestament: "Acts 14", reflection: "God establishes His covenant and shows mercy.", prompt: "How have you seen God’s covenant in your life?" },
{ day: 104, oldTestament: "2 Samuel 10-12", newTestament: "Acts 15", reflection: "God’s guidance leads even through mistakes.", prompt: "Where do you need God’s guidance despite past mistakes?" },
{ day: 105, oldTestament: "2 Samuel 13-15", newTestament: "Acts 16", reflection: "God works through trials to teach lessons.", prompt: "What trial can you reflect on for growth?" },
{ day: 106, oldTestament: "2 Samuel 16-18", newTestament: "Acts 17", reflection: "God remains faithful even when people fail.", prompt: "Where can you trust God despite human failure?" },
{ day: 107, oldTestament: "2 Samuel 19-21", newTestament: "Acts 18", reflection: "God restores what is lost through His mercy.", prompt: "What area of your life needs restoration?" },
{ day: 108, oldTestament: "2 Samuel 22-24", newTestament: "Acts 19", reflection: "God’s deliverance and strength sustain His people.", prompt: "Where do you need God’s strength today?" },
{ day: 109, oldTestament: "1 Kings 1-2", newTestament: "Acts 20", reflection: "God establishes kings and leaders for His purposes.", prompt: "How can you support God’s work in leadership?" },
{ day: 110, oldTestament: "1 Kings 3-5", newTestament: "Acts 21", reflection: "God gives wisdom to those who ask.", prompt: "What wisdom do you need from God today?" },
{ day: 111, oldTestament: "1 Kings 6-7", newTestament: "Acts 22", reflection: "God provides guidance for building His dwelling.", prompt: "How can you honor God in your personal space or work?" },
{ day: 112, oldTestament: "1 Kings 8-9", newTestament: "Acts 23", reflection: "God’s presence dwells where He is honored.", prompt: "Where can you invite God’s presence into your life?" },
{ day: 113, oldTestament: "1 Kings 10-11", newTestament: "Acts 24", reflection: "God tests hearts of leaders and rewards obedience.", prompt: "How can you stay faithful in leadership roles?" },
{ day: 114, oldTestament: "1 Kings 12-14", newTestament: "Acts 25", reflection: "God warns against disobedience and idolatry.", prompt: "Where do you need to avoid distractions from God?" },
{ day: 115, oldTestament: "1 Kings 15-17", newTestament: "Acts 26", reflection: "God raises prophets to guide His people.", prompt: "Who can you listen to for Godly guidance?" },
{ day: 116, oldTestament: "1 Kings 18-20", newTestament: "Acts 27", reflection: "God demonstrates power and sovereignty.", prompt: "Where do you see God’s power at work today?" },
{ day: 117, oldTestament: "1 Kings 21-22", newTestament: "Acts 28", reflection: "God shows justice and vindicates the righteous.", prompt: "Who do you need to pray for justice today?" },
{ day: 118, oldTestament: "2 Kings 1-3", newTestament: "Romans 1", reflection: "God’s plans continue through new generations.", prompt: "How can you trust God’s long-term plan?" },
{ day: 119, oldTestament: "2 Kings 4-6", newTestament: "Romans 2", reflection: "God provides miracles to meet His people’s needs.", prompt: "Where do you need God’s provision today?" },
{ day: 120, oldTestament: "2 Kings 7-9", newTestament: "Romans 3", reflection: "God protects His faithful even in impossible circumstances.", prompt: "Where do you need God’s protection?" },
{ day: 121, oldTestament: "2 Kings 10-12", newTestament: "Romans 4", reflection: "God rewards obedience and faithfulness.", prompt: "How can you honor God with faithful action today?" },
{ day: 122, oldTestament: "2 Kings 13-15", newTestament: "Romans 5", reflection: "God’s mercy continues despite failures.", prompt: "Reflect on God’s mercy in your life." },
{ day: 123, oldTestament: "2 Kings 16-18", newTestament: "Romans 6", reflection: "God tests and strengthens His people.", prompt: "Where can you grow stronger in faith?" },
{ day: 124, oldTestament: "2 Kings 19-21", newTestament: "Romans 7", reflection: "God delivers and judges according to His righteousness.", prompt: "How can you seek God’s righteousness today?" },
{ day: 125, oldTestament: "2 Kings 22-25", newTestament: "Romans 8", reflection: "God restores His people after judgement.", prompt: "Where do you need God’s restoration?" },
{ day: 126, oldTestament: "1 Chronicles 1-4", newTestament: "Romans 9", reflection: "God’s promises continue across generations.", prompt: "How can you honor God’s promises in your life?" },
{ day: 127, oldTestament: "1 Chronicles 5-8", newTestament: "Romans 10", reflection: "God keeps track of His people and their lineage.", prompt: "How do you see God’s care in your life history?" },
{ day: 128, oldTestament: "1 Chronicles 9-12", newTestament: "Romans 11", reflection: "God raises leaders for His plan.", prompt: "Where can you support God’s plan through leadership?" },
{ day: 129, oldTestament: "1 Chronicles 13-16", newTestament: "Romans 12", reflection: "God is glorified through worship.", prompt: "How can you worship God today in your actions?" },
{ day: 130, oldTestament: "1 Chronicles 17-20", newTestament: "Romans 13", reflection: "God establishes kings and plans for His people.", prompt: "How do you trust God’s plan in leadership transitions?" },
{ day: 131, oldTestament: "1 Chronicles 21-24", newTestament: "Romans 14", reflection: "God cares about order and worship.", prompt: "How can you organize your life to honor God?" },
{ day: 132, oldTestament: "1 Chronicles 25-29", newTestament: "Romans 15", reflection: "God equips His people for service.", prompt: "How can you serve God effectively today?" },
{ day: 133, oldTestament: "2 Chronicles 1-4", newTestament: "Romans 16", reflection: "God blesses those who seek Him.", prompt: "Where do you need God’s blessing today?" },
{ day: 134, oldTestament: "2 Chronicles 5-8", newTestament: "1 Corinthians 1", reflection: "God’s presence fills the temple when He is honored.", prompt: "How can you honor God’s presence in your life?" },
{ day: 135, oldTestament: "2 Chronicles 9-12", newTestament: "1 Corinthians 2", reflection: "God tests leaders and rewards wisdom.", prompt: "What wisdom do you need from God today?" },
{ day: 136, oldTestament: "2 Chronicles 13-16", newTestament: "1 Corinthians 3", reflection: "God’s guidance protects and strengthens.", prompt: "Where can you trust God’s guidance today?" },
{ day: 137, oldTestament: "2 Chronicles 17-20", newTestament: "1 Corinthians 4", reflection: "God delivers victory for His people.", prompt: "What challenge needs God’s deliverance today?" },
{ day: 138, oldTestament: "2 Chronicles 21-24", newTestament: "1 Corinthians 5", reflection: "God’s justice and judgment are certain.", prompt: "Where can you seek God’s justice in your life?" },
{ day: 139, oldTestament: "2 Chronicles 25-28", newTestament: "1 Corinthians 6", reflection: "God’s faithfulness continues through generations.", prompt: "How can you honor God’s faithfulness today?" },
{ day: 140, oldTestament: "2 Chronicles 29-32", newTestament: "1 Corinthians 7", reflection: "God restores and strengthens His people.", prompt: "Where do you need restoration and strength?" },
{ day: 141, oldTestament: "2 Chronicles 33-36", newTestament: "1 Corinthians 8", reflection: "God’s plans continue despite human failure.", prompt: "How can you trust God despite mistakes?" },
{ day: 142, oldTestament: "Ezra 1-3", newTestament: "1 Corinthians 9", reflection: "God leads His people to rebuild and restore.", prompt: "What is God calling you to restore today?" },
{ day: 143, oldTestament: "Ezra 4-6", newTestament: "1 Corinthians 10", reflection: "God protects His people and ensures progress.", prompt: "Where do you see God’s protection today?" },
{ day: 144, oldTestament: "Ezra 7-10", newTestament: "1 Corinthians 11", reflection: "God equips leaders for His work.", prompt: "How can you equip yourself for God’s work?" },
{ day: 145, oldTestament: "Nehemiah 1-3", newTestament: "1 Corinthians 12", reflection: "God calls us to rebuild what is broken.", prompt: "What area of life is God asking you to rebuild?" },
{ day: 146, oldTestament: "Nehemiah 4-6", newTestament: "1 Corinthians 13", reflection: "God protects and guides through opposition.", prompt: "Where do you need God’s protection today?" },
{ day: 147, oldTestament: "Nehemiah 7-9", newTestament: "1 Corinthians 14", reflection: "God calls His people to confession and repentance.", prompt: "What do you need to confess or repent of today?" },
{ day: 148, oldTestament: "Nehemiah 10-12", newTestament: "1 Corinthians 15", reflection: "God rewards faithfulness and dedication.", prompt: "How can you dedicate yourself to God today?" },
{ day: 149, oldTestament: "Nehemiah 13", newTestament: "1 Corinthians 16", reflection: "God calls for obedience and integrity.", prompt: "Where can you practice integrity today?" },
{ day: 150, oldTestament: "Esther 1-4", newTestament: "2 Corinthians 1", reflection: "God’s providence works through courageous actions.", prompt: "Where is God calling you to courage today?" },
{ day: 151, oldTestament: "Esther 5-10", newTestament: "2 Corinthians 2", reflection: "God works through courage and faithfulness.", prompt: "Where can you act courageously in faith today?" },
{ day: 152, oldTestament: "Job 1-3", newTestament: "2 Corinthians 3", reflection: "God’s sovereignty is evident even in suffering.", prompt: "How can you trust God through trials?" },
{ day: 153, oldTestament: "Job 4-7", newTestament: "2 Corinthians 4", reflection: "God allows challenges to refine and teach.", prompt: "What lesson can you learn from current challenges?" },
{ day: 154, oldTestament: "Job 8-11", newTestament: "2 Corinthians 5", reflection: "God’s justice and mercy guide His people.", prompt: "Where do you need to trust God’s justice today?" },
{ day: 155, oldTestament: "Job 12-14", newTestament: "2 Corinthians 6", reflection: "God remains faithful even when life seems unfair.", prompt: "How can you maintain faith in hard times?" },
{ day: 156, oldTestament: "Job 15-17", newTestament: "2 Corinthians 7", reflection: "God allows reflection and confession for growth.", prompt: "What area of your life needs honest reflection?" },
{ day: 157, oldTestament: "Job 18-21", newTestament: "2 Corinthians 8", reflection: "God’s wisdom surpasses human understanding.", prompt: "How can you seek God’s wisdom today?" },
{ day: 158, oldTestament: "Job 22-24", newTestament: "2 Corinthians 9", reflection: "God’s righteousness guides our choices.", prompt: "What choice can you make today according to God’s will?" },
{ day: 159, oldTestament: "Job 25-28", newTestament: "2 Corinthians 10", reflection: "God’s greatness inspires awe and humility.", prompt: "Where can you practice humility today?" },
{ day: 160, oldTestament: "Job 29-31", newTestament: "2 Corinthians 11", reflection: "God’s faithfulness sustains even in personal struggles.", prompt: "What struggle do you need God to sustain you through?" },
{ day: 161, oldTestament: "Job 32-34", newTestament: "2 Corinthians 12", reflection: "God teaches patience and dependence on Him.", prompt: "Where do you need more patience with God’s timing?" },
{ day: 162, oldTestament: "Job 35-37", newTestament: "2 Corinthians 13", reflection: "God reminds us of His majesty and control.", prompt: "How can you honor God’s majesty today?" },
{ day: 163, oldTestament: "Job 38-39", newTestament: "Galatians 1", reflection: "God shows His power and wisdom in creation.", prompt: "How do you see God’s wisdom in the world around you?" },
{ day: 164, oldTestament: "Job 40-42", newTestament: "Galatians 2", reflection: "God restores those who trust Him.", prompt: "Where can you experience God’s restoration today?" },
{ day: 165, oldTestament: "Psalms 1-4", newTestament: "Galatians 3", reflection: "God provides guidance, comfort, and hope.", prompt: "Which Psalm today speaks to your heart?" },
{ day: 166, oldTestament: "Psalms 5-8", newTestament: "Galatians 4", reflection: "God’s presence is a refuge in times of trouble.", prompt: "Where do you find refuge in God today?" },
{ day: 167, oldTestament: "Psalms 9-12", newTestament: "Galatians 5", reflection: "God calls us to justice and righteousness.", prompt: "How can you act justly today?" },
{ day: 168, oldTestament: "Psalms 13-16", newTestament: "Galatians 6", reflection: "God strengthens us in hope and trust.", prompt: "Where do you need hope and strength today?" },
{ day: 169, oldTestament: "Psalms 17-20", newTestament: "Ephesians 1", reflection: "God is our protector and guide.", prompt: "How can you rely on God’s guidance today?" },
{ day: 170, oldTestament: "Psalms 21-24", newTestament: "Ephesians 2", reflection: "God blesses and leads with mercy.", prompt: "Where do you need God’s blessing today?" },
{ day: 171, oldTestament: "Psalms 25-28", newTestament: "Ephesians 3", reflection: "God instructs and leads His people in righteousness.", prompt: "Which area of your life needs God’s direction?" },
{ day: 172, oldTestament: "Psalms 29-32", newTestament: "Ephesians 4", reflection: "God’s presence strengthens our faith.", prompt: "How can you experience God’s presence today?" },
{ day: 173, oldTestament: "Psalms 33-36", newTestament: "Ephesians 5", reflection: "God gives hope and guidance for life.", prompt: "How can you follow God’s guidance today?" },
{ day: 174, oldTestament: "Psalms 37-40", newTestament: "Ephesians 6", reflection: "God’s faithfulness is evident through all generations.", prompt: "Where can you see God’s faithfulness in your life?" },
{ day: 175, oldTestament: "Psalms 41-44", newTestament: "Philippians 1", reflection: "God restores and blesses the faithful.", prompt: "What area needs God’s restoration today?" },
{ day: 176, oldTestament: "Psalms 45-48", newTestament: "Philippians 2", reflection: "God gives wisdom and understanding.", prompt: "Where can you seek God’s wisdom today?" },
{ day: 177, oldTestament: "Psalms 49-52", newTestament: "Philippians 3", reflection: "God protects and delivers.", prompt: "Where do you need God’s protection today?" },
{ day: 178, oldTestament: "Psalms 53-56", newTestament: "Philippians 4", reflection: "God’s mercy gives peace and hope.", prompt: "Where do you need peace through God’s mercy?" },
{ day: 179, oldTestament: "Psalms 57-60", newTestament: "Colossians 1", reflection: "God strengthens His people and sustains.", prompt: "Where can you rely on God’s strength today?" },
{ day: 180, oldTestament: "Psalms 61-64", newTestament: "Colossians 2", reflection: "God provides guidance and protection.", prompt: "How can you follow God’s guidance today?" },
{ day: 181, oldTestament: "Psalms 65-68", newTestament: "Colossians 3", reflection: "God gives abundant blessings to the faithful.", prompt: "Where can you see God’s blessings today?" },
{ day: 182, oldTestament: "Psalms 69-72", newTestament: "Colossians 4", reflection: "God’s justice and mercy are evident.", prompt: "Where do you need to trust God’s justice today?" },
{ day: 183, oldTestament: "Psalms 73-76", newTestament: "1 Thessalonians 1", reflection: "God protects and strengthens in trials.", prompt: "Where do you need strength today?" },
{ day: 184, oldTestament: "Psalms 77-80", newTestament: "1 Thessalonians 2", reflection: "God leads with wisdom and mercy.", prompt: "How can you follow God’s guidance?" },
{ day: 185, oldTestament: "Psalms 81-84", newTestament: "1 Thessalonians 3", reflection: "God provides hope and direction.", prompt: "Where do you seek God’s direction today?" },
{ day: 186, oldTestament: "Psalms 85-88", newTestament: "1 Thessalonians 4", reflection: "God restores and guides faithfully.", prompt: "Where do you need restoration from God?" },
{ day: 187, oldTestament: "Psalms 89-92", newTestament: "1 Thessalonians 5", reflection: "God’s covenant remains steadfast.", prompt: "How can you trust God’s promises today?" },
{ day: 188, oldTestament: "Psalms 93-96", newTestament: "2 Thessalonians 1", reflection: "God reigns supreme and provides justice.", prompt: "How can you honor God’s reign today?" },
{ day: 189, oldTestament: "Psalms 97-100", newTestament: "2 Thessalonians 2", reflection: "God blesses those who follow Him.", prompt: "Where do you see God’s blessings in your life?" },
{ day: 190, oldTestament: "Psalms 101-104", newTestament: "2 Thessalonians 3", reflection: "God gives strength and guidance.", prompt: "Where do you need God’s strength today?" },
{ day: 191, oldTestament: "Psalms 105-108", newTestament: "1 Timothy 1", reflection: "God’s faithfulness sustains His people.", prompt: "How can you reflect God’s faithfulness today?" },
{ day: 192, oldTestament: "Psalms 109-112", newTestament: "1 Timothy 2", reflection: "God instructs and guides with wisdom.", prompt: "Where do you seek God’s wisdom today?" },
{ day: 193, oldTestament: "Psalms 113-116", newTestament: "1 Timothy 3", reflection: "God calls for integrity and service.", prompt: "How can you serve God faithfully today?" },
{ day: 194, oldTestament: "Psalms 117-118", newTestament: "1 Timothy 4", reflection: "God’s mercy and steadfast love endure.", prompt: "How can you rely on God’s mercy today?" },
{ day: 195, oldTestament: "Psalms 119:1-88", newTestament: "1 Timothy 5", reflection: "God’s word provides instruction and guidance.", prompt: "Which verse of scripture guides you today?" },
{ day: 196, oldTestament: "Psalms 119:89-176", newTestament: "1 Timothy 6", reflection: "God’s commands are eternal and reliable.", prompt: "How can you obey God’s commands today?" },
{ day: 197, oldTestament: "Psalms 120-124", newTestament: "2 Timothy 1", reflection: "God protects and leads His people.", prompt: "Where do you need God’s guidance today?" },
{ day: 198, oldTestament: "Psalms 125-128", newTestament: "2 Timothy 2", reflection: "God blesses faithfulness and obedience.", prompt: "How can you show faithfulness today?" },
{ day: 199, oldTestament: "Psalms 129-131", newTestament: "2 Timothy 3", reflection: "God’s word sustains and guides.", prompt: "Where do you seek guidance from scripture today?" },
{ day: 200, oldTestament: "Psalms 132-135", newTestament: "2 Timothy 4", reflection: "God’s faithfulness and promises endure forever.", prompt: "Reflect on God’s promises in your life today." },
{ day: 201, oldTestament: "Psalms 136-140", newTestament: "Titus 1", reflection: "God’s steadfast love endures forever.", prompt: "Where can you experience God’s love today?" },
{ day: 202, oldTestament: "Psalms 141-145", newTestament: "Titus 2", reflection: "God calls for prayer and devotion.", prompt: "How can you devote time to God today?" },
{ day: 203, oldTestament: "Psalms 146-150", newTestament: "Titus 3", reflection: "God deserves praise for all His works.", prompt: "How can you praise God today?" },
{ day: 204, oldTestament: "Proverbs 1-4", newTestament: "Philemon 1", reflection: "God’s wisdom guides our daily decisions.", prompt: "Where can you apply God’s wisdom today?" },
{ day: 205, oldTestament: "Proverbs 5-8", newTestament: "Hebrews 1", reflection: "God’s instruction protects and leads.", prompt: "What instruction can you follow today?" },
{ day: 206, oldTestament: "Proverbs 9-12", newTestament: "Hebrews 2", reflection: "God’s wisdom blesses obedience.", prompt: "How can you live wisely today?" },
{ day: 207, oldTestament: "Proverbs 13-16", newTestament: "Hebrews 3", reflection: "God strengthens those who follow His ways.", prompt: "How can you stay faithful today?" },
{ day: 208, oldTestament: "Proverbs 17-20", newTestament: "Hebrews 4", reflection: "God provides guidance and correction.", prompt: "Where do you need God’s correction today?" },
{ day: 209, oldTestament: "Proverbs 21-24", newTestament: "Hebrews 5", reflection: "God rewards integrity and righteousness.", prompt: "How can you act with integrity today?" },
{ day: 210, oldTestament: "Proverbs 25-28", newTestament: "Hebrews 6", reflection: "God provides wisdom for relationships.", prompt: "Where can you apply wisdom in relationships today?" },
{ day: 211, oldTestament: "Proverbs 29-31", newTestament: "Hebrews 7", reflection: "God honors diligence and faithfulness.", prompt: "What task requires diligence today?" },
{ day: 212, oldTestament: "Ecclesiastes 1-4", newTestament: "Hebrews 8", reflection: "God gives purpose beyond worldly pursuits.", prompt: "What purpose is God calling you to?" },
{ day: 213, oldTestament: "Ecclesiastes 5-8", newTestament: "Hebrews 9", reflection: "God desires reverence and obedience.", prompt: "Where can you show reverence today?" },
{ day: 214, oldTestament: "Ecclesiastes 9-12", newTestament: "Hebrews 10", reflection: "God’s timing is perfect.", prompt: "How can you trust God’s timing today?" },
{ day: 215, oldTestament: "Song of Solomon 1-4", newTestament: "Hebrews 11", reflection: "God’s love is reflected in relationships.", prompt: "How can you show love today?" },
{ day: 216, oldTestament: "Song of Solomon 5-8", newTestament: "Hebrews 12", reflection: "God calls us to perseverance and faith.", prompt: "Where can you persevere in faith today?" },
{ day: 217, oldTestament: "Isaiah 1-4", newTestament: "Hebrews 13", reflection: "God calls for justice and repentance.", prompt: "Where can you practice justice today?" },
{ day: 218, oldTestament: "Isaiah 5-8", newTestament: "James 1", reflection: "God warns against pride and injustice.", prompt: "How can you remain humble today?" },
{ day: 219, oldTestament: "Isaiah 9-12", newTestament: "James 2", reflection: "God brings hope and restoration.", prompt: "Where do you need hope and restoration today?" },
{ day: 220, oldTestament: "Isaiah 13-16", newTestament: "James 3", reflection: "God’s justice and power are unmatched.", prompt: "Where can you trust God’s justice?" },
{ day: 221, oldTestament: "Isaiah 17-20", newTestament: "James 4", reflection: "God calls for humility and submission.", prompt: "How can you humble yourself before God?" },
{ day: 222, oldTestament: "Isaiah 21-24", newTestament: "James 5", reflection: "God’s plans are perfect, even when unseen.", prompt: "Where can you trust God’s unseen plan?" },
{ day: 223, oldTestament: "Isaiah 25-28", newTestament: "1 Peter 1", reflection: "God’s salvation brings hope.", prompt: "How can you rejoice in God’s salvation today?" },
{ day: 224, oldTestament: "Isaiah 29-32", newTestament: "1 Peter 2", reflection: "God calls for holiness and perseverance.", prompt: "Where can you act holy today?" },
{ day: 225, oldTestament: "Isaiah 33-36", newTestament: "1 Peter 3", reflection: "God protects and delivers.", prompt: "Where do you need God’s protection?" },
{ day: 226, oldTestament: "Isaiah 37-40", newTestament: "1 Peter 4", reflection: "God’s power and mercy endure.", prompt: "Where can you rely on God’s power today?" },
{ day: 227, oldTestament: "Isaiah 41-44", newTestament: "1 Peter 5", reflection: "God strengthens and encourages.", prompt: "Where do you need God’s encouragement today?" },
{ day: 228, oldTestament: "Isaiah 45-48", newTestament: "2 Peter 1", reflection: "God fulfills His promises faithfully.", prompt: "Which promise of God can you trust today?" },
{ day: 229, oldTestament: "Isaiah 49-52", newTestament: "2 Peter 2", reflection: "God calls His people to righteousness.", prompt: "How can you pursue righteousness today?" },
{ day: 230, oldTestament: "Isaiah 53-56", newTestament: "2 Peter 3", reflection: "God’s salvation plan is perfect.", prompt: "Where do you see God’s salvation in your life?" },
{ day: 231, oldTestament: "Isaiah 57-60", newTestament: "1 John 1", reflection: "God calls us to confess and walk in light.", prompt: "What sin can you confess today?" },
{ day: 232, oldTestament: "Isaiah 61-64", newTestament: "1 John 2", reflection: "God’s love is our guide.", prompt: "How can you love others as God commands?" },
{ day: 233, oldTestament: "Isaiah 65-66", newTestament: "1 John 3", reflection: "God offers hope and restoration.", prompt: "Where do you need hope today?" },
{ day: 234, oldTestament: "Jeremiah 1-4", newTestament: "1 John 4", reflection: "God calls His people to listen and obey.", prompt: "How can you better hear God’s voice today?" },
{ day: 235, oldTestament: "Jeremiah 5-8", newTestament: "1 John 5", reflection: "God warns against disobedience.", prompt: "Where do you need to correct your actions?" },
{ day: 236, oldTestament: "Jeremiah 9-12", newTestament: "2 John 1", reflection: "God desires truth and faithfulness.", prompt: "Where can you practice faithfulness today?" },
{ day: 237, oldTestament: "Jeremiah 13-16", newTestament: "3 John 1", reflection: "God disciplines and restores.", prompt: "What area needs restoration through God’s guidance?" },
{ day: 238, oldTestament: "Jeremiah 17-20", newTestament: "Jude 1", reflection: "God calls for trust even in trials.", prompt: "Where can you trust God amidst difficulty?" },
{ day: 239, oldTestament: "Jeremiah 21-24", newTestament: "Revelation 1", reflection: "God’s plans bring hope and justice.", prompt: "Where can you place hope in God’s plan?" },
{ day: 240, oldTestament: "Jeremiah 25-28", newTestament: "Revelation 2", reflection: "God calls His people to repentance.", prompt: "Where can you repent and align with God today?" },
{ day: 241, oldTestament: "Jeremiah 29-32", newTestament: "Revelation 3", reflection: "God promises restoration and blessing.", prompt: "What blessing from God can you celebrate today?" },
{ day: 242, oldTestament: "Jeremiah 33-36", newTestament: "Revelation 4", reflection: "God reigns and His plans are perfect.", prompt: "How can you acknowledge God’s sovereignty today?" },
{ day: 243, oldTestament: "Jeremiah 37-40", newTestament: "Revelation 5", reflection: "God’s faithfulness endures through challenges.", prompt: "Where do you see God’s faithfulness in your life?" },
{ day: 244, oldTestament: "Jeremiah 41-44", newTestament: "Revelation 6", reflection: "God judges righteously and protects the faithful.", prompt: "Where do you seek God’s protection today?" },
{ day: 245, oldTestament: "Jeremiah 45-48", newTestament: "Revelation 7", reflection: "God calls His people to persevere.", prompt: "Where can you persevere in faith today?" },
{ day: 246, oldTestament: "Jeremiah 49-52", newTestament: "Revelation 8", reflection: "God’s justice and mercy are perfect.", prompt: "How can you trust God’s justice today?" },
{ day: 247, oldTestament: "Lamentations 1-3", newTestament: "Revelation 9", reflection: "God’s compassion comforts in sorrow.", prompt: "Where do you need God’s comfort today?" },
{ day: 248, oldTestament: "Lamentations 4-5", newTestament: "Revelation 10", reflection: "God restores those who seek Him.", prompt: "Where can you receive restoration from God?" },
{ day: 249, oldTestament: "Ezekiel 1-4", newTestament: "Revelation 11", reflection: "God shows His glory even in challenging times.", prompt: "Where do you see God’s glory today?" },
{ day: 250, oldTestament: "Ezekiel 5-8", newTestament: "Revelation 12", reflection: "God calls for repentance and faithfulness.", prompt: "How can you respond faithfully to God today?" },
{ day: 251, oldTestament: "Ezekiel 9-12", newTestament: "Revelation 13", reflection: "God’s justice and holiness are revealed.", prompt: "Where do you need to trust God’s justice today?" },
{ day: 252, oldTestament: "Ezekiel 13-16", newTestament: "Revelation 14", reflection: "God warns against deception and idolatry.", prompt: "Where can you remain vigilant against falsehoods?" },
{ day: 253, oldTestament: "Ezekiel 17-20", newTestament: "Revelation 15", reflection: "God’s faithfulness calls for obedience.", prompt: "Where can you obey God more fully today?" },
{ day: 254, oldTestament: "Ezekiel 21-24", newTestament: "Revelation 16", reflection: "God’s judgment is righteous and perfect.", prompt: "How can you reflect God’s righteousness in your actions?" },
{ day: 255, oldTestament: "Ezekiel 25-28", newTestament: "Revelation 17", reflection: "God demonstrates His sovereignty over nations.", prompt: "Where can you trust God’s sovereignty today?" },
{ day: 256, oldTestament: "Ezekiel 29-32", newTestament: "Revelation 18", reflection: "God’s power and plans prevail.", prompt: "How can you rely on God’s power today?" },
{ day: 257, oldTestament: "Ezekiel 33-36", newTestament: "Revelation 19", reflection: "God calls for repentance and restoration.", prompt: "Where do you need God’s restoration today?" },
{ day: 258, oldTestament: "Ezekiel 37-40", newTestament: "Revelation 20", reflection: "God gives hope and life to the hopeless.", prompt: "Where can you experience God’s hope today?" },
{ day: 259, oldTestament: "Ezekiel 41-44", newTestament: "Revelation 21", reflection: "God’s plan for restoration is perfect.", prompt: "How can you trust God’s plan for your future?" },
{ day: 260, oldTestament: "Ezekiel 45-48", newTestament: "Revelation 22", reflection: "God’s promises bring hope and completion.", prompt: "Reflect on God’s faithfulness in your life." },
{ day: 261, oldTestament: "Daniel 1-3", newTestament: "Matthew 1", reflection: "God preserves and protects His faithful.", prompt: "Where do you need God’s protection today?" },
{ day: 262, oldTestament: "Daniel 4-6", newTestament: "Matthew 2", reflection: "God humbles the proud and exalts the faithful.", prompt: "How can you humble yourself before God?" },
{ day: 263, oldTestament: "Daniel 7-9", newTestament: "Matthew 3", reflection: "God’s sovereignty is eternal.", prompt: "Where can you trust God’s eternal plan?" },
{ day: 264, oldTestament: "Daniel 10-12", newTestament: "Matthew 4", reflection: "God strengthens for trials and tests.", prompt: "Where do you need God’s strength today?" },
{ day: 265, oldTestament: "Hosea 1-4", newTestament: "Matthew 5", reflection: "God calls His people to love and repentance.", prompt: "How can you act in love and obedience today?" },
{ day: 266, oldTestament: "Hosea 5-8", newTestament: "Matthew 6", reflection: "God warns against unfaithfulness.", prompt: "Where can you renew your faithfulness to God?" },
{ day: 267, oldTestament: "Hosea 9-14", newTestament: "Matthew 7", reflection: "God’s mercy offers restoration.", prompt: "Where do you need God’s mercy today?" },
{ day: 268, oldTestament: "Joel 1-3", newTestament: "Matthew 8", reflection: "God calls for repentance and trust.", prompt: "How can you trust God more fully today?" },
{ day: 269, oldTestament: "Amos 1-5", newTestament: "Matthew 9", reflection: "God calls for justice and righteousness.", prompt: "Where can you practice justice today?" },
{ day: 270, oldTestament: "Amos 6-9", newTestament: "Matthew 10", reflection: "God warns against complacency.", prompt: "How can you remain vigilant in faith?" },
{ day: 271, oldTestament: "Obadiah 1", newTestament: "Matthew 11", reflection: "God sees all and judges righteously.", prompt: "Where can you trust God’s judgment today?" },
{ day: 272, oldTestament: "Jonah 1-4", newTestament: "Matthew 12", reflection: "God shows mercy even to those who stray.", prompt: "Who can you show mercy to today?" },
{ day: 273, oldTestament: "Micah 1-4", newTestament: "Matthew 13", reflection: "God calls for justice and humility.", prompt: "How can you practice humility today?" },
{ day: 274, oldTestament: "Micah 5-7", newTestament: "Matthew 14", reflection: "God’s plan is perfect and faithful.", prompt: "Where can you trust God’s plan today?" },
{ day: 275, oldTestament: "Nahum 1-3", newTestament: "Matthew 15", reflection: "God’s justice and power prevail.", prompt: "Where can you rely on God’s power?" },
{ day: 276, oldTestament: "Habakkuk 1-3", newTestament: "Matthew 16", reflection: "God is sovereign over all circumstances.", prompt: "How can you surrender control to God today?" },
{ day: 277, oldTestament: "Zephaniah 1-3", newTestament: "Matthew 17", reflection: "God calls for repentance and faithfulness.", prompt: "Where can you align yourself with God’s will?" },
{ day: 278, oldTestament: "Haggai 1-2", newTestament: "Matthew 18", reflection: "God encourages rebuilding and obedience.", prompt: "What can you rebuild in your life with God’s help?" },
{ day: 279, oldTestament: "Zechariah 1-4", newTestament: "Matthew 19", reflection: "God empowers His people for His work.", prompt: "Where do you need God’s empowerment today?" },
{ day: 280, oldTestament: "Zechariah 5-8", newTestament: "Matthew 20", reflection: "God calls for faithfulness and vision.", prompt: "How can you be faithful to God’s vision today?" },
{ day: 281, oldTestament: "Zechariah 9-14", newTestament: "Matthew 21", reflection: "God’s promises are sure.", prompt: "Which promise of God encourages you today?" },
{ day: 282, oldTestament: "Malachi 1-4", newTestament: "Matthew 22", reflection: "God calls for obedience and love.", prompt: "How can you obey God fully today?" },
{ day: 283, oldTestament: "Matthew 1-4", newTestament: "Mark 1", reflection: "God’s plan unfolds through Jesus.", prompt: "How can you follow Christ’s example today?" },
{ day: 284, oldTestament: "Matthew 5-8", newTestament: "Mark 2", reflection: "God teaches His people to live in righteousness.", prompt: "Where can you apply God’s teaching today?" },
{ day: 285, oldTestament: "Matthew 9-12", newTestament: "Mark 3", reflection: "God’s power and mercy are evident.", prompt: "How have you seen God’s mercy today?" },
{ day: 286, oldTestament: "Matthew 13-16", newTestament: "Mark 4", reflection: "God’s wisdom and guidance protect us.", prompt: "Where do you need God’s guidance today?" },
{ day: 287, oldTestament: "Matthew 17-20", newTestament: "Mark 5", reflection: "God calls for faith and trust.", prompt: "Where can you exercise faith today?" },
{ day: 288, oldTestament: "Matthew 21-24", newTestament: "Mark 6", reflection: "God prepares His people for service.", prompt: "How can you serve God today?" },
{ day: 289, oldTestament: "Matthew 25-28", newTestament: "Mark 7", reflection: "God’s plan brings salvation.", prompt: "How can you share God’s salvation with others?" },
{ day: 290, oldTestament: "Mark 8-11", newTestament: "Mark 8", reflection: "God teaches humility and obedience.", prompt: "Where can you practice humility today?" },
{ day: 291, oldTestament: "Mark 12-16", newTestament: "Luke 1", reflection: "God’s mercy and grace are revealed.", prompt: "How can you reflect God’s grace today?" },
{ day: 292, oldTestament: "Luke 2-5", newTestament: "Luke 6", reflection: "God calls for love and service.", prompt: "Where can you show love today?" },
{ day: 293, oldTestament: "Luke 6-9", newTestament: "Luke 10", reflection: "God provides guidance and wisdom.", prompt: "Where do you need God’s wisdom today?" },
{ day: 294, oldTestament: "Luke 10-13", newTestament: "Luke 14", reflection: "God strengthens His people for trials.", prompt: "Where do you need God’s strength today?" },
{ day: 295, oldTestament: "Luke 14-17", newTestament: "Luke 18", reflection: "God calls for perseverance in faith.", prompt: "How can you persevere in your faith today?" },
{ day: 296, oldTestament: "Luke 18-21", newTestament: "Luke 19", reflection: "God works through challenges to teach lessons.", prompt: "What lesson is God teaching you today?" },
{ day: 297, oldTestament: "Luke 22-24", newTestament: "Luke 20", reflection: "God’s plan brings redemption and hope.", prompt: "Where do you see God’s redemption today?" },
{ day: 298, oldTestament: "John 1-4", newTestament: "John 5", reflection: "God reveals Himself through Christ.", prompt: "How can you know Christ more today?" },
{ day: 299, oldTestament: "John 5-8", newTestament: "John 9", reflection: "God brings light to those in darkness.", prompt: "Where do you need God’s light today?" },
{ day: 300, oldTestament: "John 9-12", newTestament: "John 13", reflection: "God teaches love and service through Jesus.", prompt: "How can you serve others as Jesus did today?" },
{ day: 301, oldTestament: "John 13-16", newTestament: "John 14", reflection: "God comforts and guides through His Spirit.", prompt: "Where do you need God’s comfort today?" },
{ day: 302, oldTestament: "John 16-19", newTestament: "John 15", reflection: "God calls us to love one another.", prompt: "Who can you show love to today?" },
{ day: 303, oldTestament: "John 19-21", newTestament: "Acts 1", reflection: "God fulfills His promises and sends the Spirit.", prompt: "How can you live empowered by the Spirit?" },
{ day: 304, oldTestament: "Acts 2-5", newTestament: "Acts 6", reflection: "God works through His people to spread the gospel.", prompt: "Where can you serve God’s mission today?" },
{ day: 305, oldTestament: "Acts 6-9", newTestament: "Acts 10", reflection: "God transforms lives and hearts.", prompt: "How has God transformed your life?" },
{ day: 306, oldTestament: "Acts 10-13", newTestament: "Acts 14", reflection: "God’s plan reaches all nations.", prompt: "Where can you share God’s love beyond your comfort zone?" },
{ day: 307, oldTestament: "Acts 15-18", newTestament: "Acts 19", reflection: "God empowers and strengthens His servants.", prompt: "Where do you need God’s strength today?" },
{ day: 308, oldTestament: "Acts 20-23", newTestament: "Acts 24", reflection: "God guides in difficult circumstances.", prompt: "Where do you need God’s guidance today?" },
{ day: 309, oldTestament: "Acts 24-27", newTestament: "Acts 28", reflection: "God preserves His people and fulfills His promises.", prompt: "How can you trust God’s protection today?" },
{ day: 310, oldTestament: "Romans 1-4", newTestament: "Romans 5", reflection: "God’s grace brings salvation.", prompt: "Where can you rely on God’s grace today?" },
{ day: 311, oldTestament: "Romans 6-9", newTestament: "Romans 10", reflection: "God calls for faith and obedience.", prompt: "How can you obey God’s call today?" },
{ day: 312, oldTestament: "Romans 11-14", newTestament: "Romans 15", reflection: "God’s promises are sure and eternal.", prompt: "Which of God’s promises gives you hope today?" },
{ day: 313, oldTestament: "Romans 15-16", newTestament: "1 Corinthians 1", reflection: "God unites His people through love.", prompt: "How can you foster unity today?" },
{ day: 314, oldTestament: "1 Corinthians 2-5", newTestament: "1 Corinthians 6", reflection: "God calls for holiness and integrity.", prompt: "Where can you act with integrity today?" },
{ day: 315, oldTestament: "1 Corinthians 6-9", newTestament: "1 Corinthians 10", reflection: "God provides guidance and protection.", prompt: "Where do you need God’s guidance today?" },
{ day: 316, oldTestament: "1 Corinthians 10-13", newTestament: "1 Corinthians 14", reflection: "God calls for love and spiritual growth.", prompt: "How can you grow in love today?" },
{ day: 317, oldTestament: "1 Corinthians 14-16", newTestament: "2 Corinthians 1", reflection: "God comforts and encourages the faithful.", prompt: "Where do you need God’s comfort today?" },
{ day: 318, oldTestament: "2 Corinthians 2-5", newTestament: "2 Corinthians 6", reflection: "God strengthens through trials.", prompt: "Where do you need God’s strength today?" },
{ day: 319, oldTestament: "2 Corinthians 6-9", newTestament: "2 Corinthians 10", reflection: "God equips for service and ministry.", prompt: "Where can you serve others today?" },
{ day: 320, oldTestament: "2 Corinthians 10-13", newTestament: "Galatians 1", reflection: "God calls for faith and righteousness.", prompt: "How can you pursue righteousness today?" },
{ day: 321, oldTestament: "Galatians 2-6", newTestament: "Ephesians 1", reflection: "God’s grace empowers His people.", prompt: "How can you rely on God’s grace today?" },
{ day: 322, oldTestament: "Ephesians 2-6", newTestament: "Philippians 1", reflection: "God calls for humility and unity.", prompt: "How can you practice humility today?" },
{ day: 323, oldTestament: "Philippians 2-4", newTestament: "Colossians 1", reflection: "God strengthens hearts through faith.", prompt: "Where do you need God’s strength today?" },
{ day: 324, oldTestament: "Colossians 2-4", newTestament: "1 Thessalonians 1", reflection: "God calls for perseverance and hope.", prompt: "Where can you persevere in hope today?" },
{ day: 325, oldTestament: "1 Thessalonians 2-5", newTestament: "2 Thessalonians 1", reflection: "God provides guidance and encouragement.", prompt: "Where do you need God’s encouragement today?" },
{ day: 326, oldTestament: "1 Timothy 1-6", newTestament: "2 Timothy 1", reflection: "God calls for faithfulness and teaching.", prompt: "How can you be faithful today?" },
{ day: 327, oldTestament: "2 Timothy 2-4", newTestament: "Titus 1", reflection: "God strengthens leaders and servants.", prompt: "Where do you need God’s guidance in leadership?" },
{ day: 328, oldTestament: "Titus 2-3", newTestament: "Philemon 1", reflection: "God encourages reconciliation and forgiveness.", prompt: "Where can you offer forgiveness today?" },
{ day: 329, oldTestament: "Hebrews 1-4", newTestament: "Hebrews 5", reflection: "God’s supremacy and mercy are evident.", prompt: "Where can you trust God’s supremacy today?" },
{ day: 330, oldTestament: "Hebrews 5-9", newTestament: "Hebrews 10", reflection: "God calls for faith, obedience, and hope.", prompt: "How can you obey God fully today?" },
{ day: 331, oldTestament: "Hebrews 10-13", newTestament: "James 1", reflection: "God strengthens and encourages.", prompt: "Where do you need God’s strength today?" },
{ day: 332, oldTestament: "James 2-5", newTestament: "1 Peter 1", reflection: "God calls for perseverance and holy living.", prompt: "How can you live faithfully today?" },
{ day: 333, oldTestament: "1 Peter 2-5", newTestament: "2 Peter 1", reflection: "God provides hope and guidance.", prompt: "Where do you need God’s guidance today?" },
{ day: 334, oldTestament: "2 Peter 2-3", newTestament: "1 John 1", reflection: "God calls for truth and love.", prompt: "How can you reflect God’s love today?" },
{ day: 335, oldTestament: "1 John 2-5", newTestament: "2 John 1", reflection: "God provides guidance and protection.", prompt: "Where do you need God’s protection today?" },
{ day: 336, oldTestament: "3 John 1", newTestament: "Jude 1", reflection: "God calls for faithfulness and integrity.", prompt: "Where can you act faithfully today?" },
{ day: 337, oldTestament: "Revelation 1-3", newTestament: "Revelation 4", reflection: "God’s plan is unfolding.", prompt: "How can you align with God’s plan today?" },
{ day: 338, oldTestament: "Revelation 4-6", newTestament: "Revelation 7", reflection: "God’s sovereignty and justice prevail.", prompt: "Where can you trust God’s justice today?" },
{ day: 339, oldTestament: "Revelation 7-9", newTestament: "Revelation 10", reflection: "God calls for perseverance and faith.", prompt: "How can you persevere in faith today?" },
{ day: 340, oldTestament: "Revelation 10-12", newTestament: "Revelation 13", reflection: "God protects and empowers His people.", prompt: "Where do you need God’s protection today?" },
{ day: 341, oldTestament: "Revelation 13-15", newTestament: "Revelation 16", reflection: "God’s plans are perfect and just.", prompt: "How can you trust God’s plans today?" },
{ day: 342, oldTestament: "Revelation 16-18", newTestament: "Revelation 19", reflection: "God calls for worship and faith.", prompt: "Where can you worship God today?" },
{ day: 343, oldTestament: "Revelation 19-21", newTestament: "Revelation 22", reflection: "God brings redemption and hope.", prompt: "How can you rejoice in God’s redemption today?" },
{ day: 344, oldTestament: "Genesis 1-2", newTestament: "Matthew 1", reflection: "God’s creation and plan inspire awe.", prompt: "Where do you see God’s handiwork today?" },
{ day: 345, oldTestament: "Exodus 1-3", newTestament: "Matthew 2", reflection: "God leads His people with guidance.", prompt: "Where can you follow God’s guidance today?" },
{ day: 346, oldTestament: "Leviticus 1-3", newTestament: "Matthew 3", reflection: "God’s instructions teach holiness.", prompt: "How can you live in holiness today?" },
{ day: 347, oldTestament: "Numbers 1-3", newTestament: "Matthew 4", reflection: "God organizes and protects His people.", prompt: "Where do you need God’s protection today?" },
{ day: 348, oldTestament: "Deuteronomy 1-3", newTestament: "Matthew 5", reflection: "God provides guidance for life.", prompt: "Where do you need God’s guidance today?" },
{ day: 349, oldTestament: "Joshua 1-3", newTestament: "Matthew 6", reflection: "God strengthens and directs.", prompt: "Where do you need God’s strength today?" },
{ day: 350, oldTestament: "Judges 1-3", newTestament: "Matthew 7", reflection: "God leads in victory and justice.", prompt: "How can you trust God’s leading today?" },
{ day: 351, oldTestament: "Ruth 1-4", newTestament: "Matthew 8", reflection: "God rewards faithfulness and loyalty.", prompt: "Where can you be faithful today?" },
{ day: 352, oldTestament: "1 Samuel 1-3", newTestament: "Matthew 9", reflection: "God hears and answers prayers.", prompt: "What prayer do you bring to God today?" },
{ day: 353, oldTestament: "1 Samuel 4-7", newTestament: "Matthew 10", reflection: "God leads and protects His people.", prompt: "Where do you seek God’s protection today?" },
{ day: 354, oldTestament: "1 Samuel 8-12", newTestament: "Matthew 11", reflection: "God calls for obedience and trust.", prompt: "How can you obey God fully today?" },
{ day: 355, oldTestament: "2 Samuel 1-4", newTestament: "Matthew 12", reflection: "God strengthens in leadership and trials.", prompt: "Where do you need God’s guidance today?" },
{ day: 356, oldTestament: "2 Samuel 5-8", newTestament: "Matthew 13", reflection: "God blesses faithfulness and service.", prompt: "How can you serve God today?" },
{ day: 357, oldTestament: "2 Samuel 9-12", newTestament: "Matthew 14", reflection: "God’s forgiveness and mercy endure.", prompt: "Where do you need God’s mercy today?" },
{ day: 358, oldTestament: "1 Kings 1-4", newTestament: "Matthew 15", reflection: "God provides wisdom and guidance.", prompt: "Where do you seek God’s wisdom today?" },
{ day: 359, oldTestament: "1 Kings 5-8", newTestament: "Matthew 16", reflection: "God blesses obedience and diligence.", prompt: "How can you be diligent in God’s work today?" },
{ day: 360, oldTestament: "1 Kings 9-12", newTestament: "Matthew 17", reflection: "God calls for integrity and faith.", prompt: "Where can you act faithfully today?" },
{ day: 361, oldTestament: "2 Kings 13-16", newTestament: "Matthew 18", reflection: "God strengthens in challenges.", prompt: "Where do you need God’s strength today?" },
{ day: 362, oldTestament: "2 Kings 17-20", newTestament: "Matthew 19", reflection: "God guides and protects His people.", prompt: "How can you follow God’s guidance today?" },
{ day: 363, oldTestament: "2 Kings 21-24", newTestament: "Matthew 20", reflection: "God remains faithful to His promises.", prompt: "Where do you see God’s faithfulness today?" },
{ day: 364, oldTestament: "2 Kings 25", newTestament: "Matthew 21", reflection: "God offers hope and restoration.", prompt: "How can you trust God’s restoration today?" },
{ day: 365, oldTestament: "Malachi 3-4", newTestament: "Revelation 22", reflection: "God’s promises come full circle, ending with hope and restoration.", prompt: "Reflect on God’s faithfulness throughout this year." }
  ];
